title: Bikepacking
author: Kyrre Havik
email: Kyrremann@gmail.com
description: >-
  A place where I will document my bikepacking trips, the dates for the post is the day the trip started.

favicon: icons8-bicycle-96.png
goat_counter: kyrremann
remote_theme: riggraz/no-style-please

theme_config:
  back_home_text: "back"
  date_format: "%Y-%m-%d"
  show_description: true
